version: '3.8'

volumes:
  postgres:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata:rw
    env_file:
      - .env-docker
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata

  app:
    build: .
    container_name: nearest_cars_app.app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env-docker
    command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
