"""Initial migration

Revision ID: 314ae9380aa5
Revises: 
Create Date: 2023-05-25 11:30:18.031386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314ae9380aa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
